using Avalonia.Platform;

namespace LoupixDeck.Services.StarterProfiles;

/// <summary>Puts the wallpapers and animations shipped for the starter profiles into the asset store.</summary>
public interface IStarterArt
{
    /// <summary>
    /// Stores the shipped file <paramref name="fileName"/> (from <c>Assets/StarterProfiles</c>) in the
    /// asset store under <paramref name="subFolder"/> and returns its relative asset path, or null when
    /// it cannot be read.
    /// </summary>
    string Import(string fileName, string subFolder);
}

/// <summary>
/// Reads the starter profile art from the app's resources (generated by
/// <c>tools/StarterProfileArt/generate_art.py</c>). The asset store is content-addressed, so creating
/// the same starter profile twice stores each file once.
/// </summary>
public sealed class StarterArt(IAssetService assets) : IStarterArt
{
    private const string ResourceBase = "avares://LoupixDeck/Assets/StarterProfiles/";

    public string Import(string fileName, string subFolder)
    {
        try
        {
            using Stream stream = AssetLoader.Open(new Uri(ResourceBase + fileName));
            using MemoryStream buffer = new();
            stream.CopyTo(buffer);
            return assets.Import(buffer.ToArray(), Path.GetExtension(fileName), subFolder);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            Console.WriteLine($"[StarterProfiles] Could not store '{fileName}': {ex.Message}");
            return null;
        }
    }
}