name: .NET Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    env:
      PROJECT_PATH: ./LoupixDeck.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: |
          $tag = "$env:GITHUB_REF"
          $version = $tag -replace 'refs/tags/v', ''
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Debug version
        run: echo "Set version to $env:VERSION"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore $env:PROJECT_PATH

      - name: Publish for Windows
        run: |
          dotnet publish $env:PROJECT_PATH -c Release -r win-x64 --self-contained true `
            /p:PublishSingleFile=true `
            /p:PublishTrimmed=false `
            /p:EnableCompressionInSingleFile=true `
            /p:ReadyToRun=true `
            /p:Version=$env:VERSION `
            -o publish/win-x64

      - name: Zip Windows build
        run: Compress-Archive -Path publish/win-x64/* -DestinationPath LoupixDeck-win-x64.zip

      - name: Upload Windows zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: LoupixDeck-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./LoupixDeck.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish for Linux
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -r linux-x64 --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=false \
            /p:EnableCompressionInSingleFile=true \
            /p:ReadyToRun=true \
            /p:Version=${{ env.VERSION }} \
            -o publish/linux-x64

      - name: Tar Linux build
        run: |
          cd publish/linux-x64
          tar -czvf ../../LoupixDeck-linux-x64.tar.gz .

      - name: Upload Linux tar.gz to release
        uses: softprops/action-gh-release@v2
        with:
          files: LoupixDeck-linux-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
